### PR TITLE
fix(grammar): combination of call expression, member expression, and binary operator

### LINKED ISSUE #8: Bug: wrong syntax highlighting for multiple static method calls, e.g. `Math.cos`
Here's a minimal reproducible jai code with wrong syntax highlighting:
```jai
Math :: #import "Math";

main :: () {
    t := Math.cos(30) +
         Math.cos(30) +
         Math.cos(30) +
         Math.cos(30);
}
```

Image

---

### OK: when `Math.cos` is changed to `cos`

Image

### OK: when there's only two `Math.cos` in one expression

Image

### NOT OK: when it's a struct

Image

### PR DESCRIPTION
**Pull request by lungsin**
Fix #8 

This PR modify the call_expression and member_expression so that it's resolved in a complex statement by making the rule left recursive. Previously  `member_expression` was both left and right recursive and somehow this makes member_expression unresolved until the end of the statement and causing error.

### CODE REVIEW

File: src/parser.c
Comment (lungsin) [inline src/parser.c:1]: This is the result of `tree-sitter generate`. Idk why the diff is so large, hopefully it's expected.

File: test/corpus/statements.txt [hunk 1]
```diff
@@ -0,0 +1,81 @@
+================================================================================
+member function call
+================================================================================
+
+t := Math.cos(1) + Math.cos(2) + Math.cos(3);
```
Comment (lungsin) [inline test/corpus/statements.txt:5]: Added a bunch of new corpus tests

File: queries/indents.scm [hunk 2]
```diff
@@ -33,7 +33,7 @@
 (if_statement_condition_and_consequence
   consequence: (_
     ";" @indent.end) @_consequence
-  (#not-match? @_consequence "{")
+  (#not-match? @_consequence "\\{")
```
Comment (lungsin) [inline queries/indents.scm:36]: Added escape sequence because `tree-sitter test` warns about regex thingy

File: test/corpus/declarations.txt
Comment (lungsin) [inline test/corpus/declarations.txt:1]: Updated this test because a few commits ago, we remove `top_level_declarations`

File: grammar.js [hunk 3]
```diff
@@ -770,9 +770,7 @@ module.exports = grammar({
             )),
             '.',
             prec.left(choice(
-                $.member_expression,
```
Comment (lungsin) [inline grammar.js:773]: Remove this because `member_expression` is already handled in the lhs above.

File: grammar.js [hunk 4]
```diff
@@ -770,9 +770,7 @@ module.exports = grammar({
...
                 $.identifier,
-                $.call_expression,
```
Comment (lungsin) [inline grammar.js:775]: Make the call expression the parent node instead, the node structure becomes something like this:
```
(call_expression 
   (member_expression ...) 
   (arguments ...) )
```

**Review by lungsin — COMMENTED** [review]
Added self review with the hope to make the intent of this PR clearer

File: src/parser.c
Comment (J-Chris-Findlay-RESIDEO) [reply src/parser.c:1]: version difference?

Comment (lungsin) [reply src/parser.c:1]: Yeah, that seems to be the case. Unfortunately, it broke the existing `scanner.c` and it crashed on constatitus machine, but not on my machine somehow.

He provided a patch to the `scanner.c` though. So hopefully it's fine now.
